//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainGeneralizedCodeNS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas-qad-com:xml-services", ConfigurationName="MaintainGeneralizedCodeNS.QdocWebService")]
    public interface QdocWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeResponse> maintainGeneralizedCodeAsync(MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType
    {
        
        private bool suppressResponseDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=0)]
        public bool suppressResponseDetail
        {
            get
            {
                return this.suppressResponseDetailField;
            }
            set
            {
                this.suppressResponseDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReplyToType
    {
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class GeneralizedCodeResponseType
    {
        
        private string codeFldnameField;
        
        private string codeValueField;
        
        private string codeGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codeFldname
        {
            get
            {
                return this.codeFldnameField;
            }
            set
            {
                this.codeFldnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codeValue
        {
            get
            {
                return this.codeValueField;
            }
            set
            {
                this.codeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string codeGroup
        {
            get
            {
                return this.codeGroupField;
            }
            set
            {
                this.codeGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services:common")]
    public partial class Temp_err_msg
    {
        
        private System.Nullable<int> tt_levelField;
        
        private string tt_msg_contextField;
        
        private string tt_msg_dataField;
        
        private string tt_msg_datetimeField;
        
        private string tt_msg_descField;
        
        private string tt_msg_fieldField;
        
        private System.Nullable<int> tt_msg_indexField;
        
        private string[] tt_msg_keysField;
        
        private string tt_msg_nbrField;
        
        private System.Nullable<bool> tt_msg_processedField;
        
        private string tt_msg_sevField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> tt_level
        {
            get
            {
                return this.tt_levelField;
            }
            set
            {
                this.tt_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tt_msg_context
        {
            get
            {
                return this.tt_msg_contextField;
            }
            set
            {
                this.tt_msg_contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string tt_msg_data
        {
            get
            {
                return this.tt_msg_dataField;
            }
            set
            {
                this.tt_msg_dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string tt_msg_datetime
        {
            get
            {
                return this.tt_msg_datetimeField;
            }
            set
            {
                this.tt_msg_datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string tt_msg_desc
        {
            get
            {
                return this.tt_msg_descField;
            }
            set
            {
                this.tt_msg_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string tt_msg_field
        {
            get
            {
                return this.tt_msg_fieldField;
            }
            set
            {
                this.tt_msg_fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> tt_msg_index
        {
            get
            {
                return this.tt_msg_indexField;
            }
            set
            {
                this.tt_msg_indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tt_msg_keys", IsNullable=true, Order=7)]
        public string[] tt_msg_keys
        {
            get
            {
                return this.tt_msg_keysField;
            }
            set
            {
                this.tt_msg_keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string tt_msg_nbr
        {
            get
            {
                return this.tt_msg_nbrField;
            }
            set
            {
                this.tt_msg_nbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> tt_msg_processed
        {
            get
            {
                return this.tt_msg_processedField;
            }
            set
            {
                this.tt_msg_processedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string tt_msg_sev
        {
            get
            {
                return this.tt_msg_sevField;
            }
            set
            {
                this.tt_msg_sevField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class WSDLMaintainGeneralizedCodeResponseType
    {
        
        private string resultField;
        
        private TtContext[] dsSessionContextField;
        
        private Temp_err_msg[] dsExceptionsField;
        
        private GeneralizedCodeResponseType[] dsGeneralizedCodeResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttContext", IsNullable=false)]
        public TtContext[] dsSessionContext
        {
            get
            {
                return this.dsSessionContextField;
            }
            set
            {
                this.dsSessionContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("temp_err_msg", IsNullable=false)]
        public Temp_err_msg[] dsExceptions
        {
            get
            {
                return this.dsExceptionsField;
            }
            set
            {
                this.dsExceptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("generalizedCode", IsNullable=false)]
        public GeneralizedCodeResponseType[] dsGeneralizedCodeResponse
        {
            get
            {
                return this.dsGeneralizedCodeResponseField;
            }
            set
            {
                this.dsGeneralizedCodeResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services:common")]
    public partial class TtContext
    {
        
        private string propertyQualifierField;
        
        private string propertyNameField;
        
        private string propertyValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string propertyQualifier
        {
            get
            {
                return this.propertyQualifierField;
            }
            set
            {
                this.propertyQualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string propertyName
        {
            get
            {
                return this.propertyNameField;
            }
            set
            {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string propertyValue
        {
            get
            {
                return this.propertyValueField;
            }
            set
            {
                this.propertyValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class GeneralizedCodeType
    {
        
        private string operationField;
        
        private string codeFldnameField;
        
        private string codeValueField;
        
        private string codeCmmtField;
        
        private string codeGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codeFldname
        {
            get
            {
                return this.codeFldnameField;
            }
            set
            {
                this.codeFldnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string codeValue
        {
            get
            {
                return this.codeValueField;
            }
            set
            {
                this.codeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string codeCmmt
        {
            get
            {
                return this.codeCmmtField;
            }
            set
            {
                this.codeCmmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string codeGroup
        {
            get
            {
                return this.codeGroupField;
            }
            set
            {
                this.codeGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas-qad-com:xml-services")]
    public partial class WSDLMaintainGeneralizedCodeType
    {
        
        private TtContext[] dsSessionContextField;
        
        private GeneralizedCodeType[] dsGeneralizedCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:schemas-qad-com:xml-services:common", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ttContext", IsNullable=false)]
        public TtContext[] dsSessionContext
        {
            get
            {
                return this.dsSessionContextField;
            }
            set
            {
                this.dsSessionContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("generalizedCode", IsNullable=false)]
        public GeneralizedCodeType[] dsGeneralizedCode
        {
            get
            {
                return this.dsGeneralizedCodeField;
            }
            set
            {
                this.dsGeneralizedCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMaintainGeneralizedCodeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string MessageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public MaintainGeneralizedCodeNS.ReferenceParametersType ReferenceParameters;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public MaintainGeneralizedCodeNS.ReplyToType ReplyTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-qad-com:xml-services", Order=0)]
        public MaintainGeneralizedCodeNS.WSDLMaintainGeneralizedCodeType maintainGeneralizedCode;
        
        public processMaintainGeneralizedCodeRequest()
        {
        }
        
        public processMaintainGeneralizedCodeRequest(string Action, string To, string MessageID, MaintainGeneralizedCodeNS.ReferenceParametersType ReferenceParameters, MaintainGeneralizedCodeNS.ReplyToType ReplyTo, MaintainGeneralizedCodeNS.WSDLMaintainGeneralizedCodeType maintainGeneralizedCode)
        {
            this.Action = Action;
            this.To = To;
            this.MessageID = MessageID;
            this.ReferenceParameters = ReferenceParameters;
            this.ReplyTo = ReplyTo;
            this.maintainGeneralizedCode = maintainGeneralizedCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMaintainGeneralizedCodeResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string MessageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public string RelatesTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:schemas-qad-com:xml-services", Order=0)]
        public MaintainGeneralizedCodeNS.WSDLMaintainGeneralizedCodeResponseType maintainGeneralizedCodeResponse;
        
        public processMaintainGeneralizedCodeResponse()
        {
        }
        
        public processMaintainGeneralizedCodeResponse(string To, string Action, string MessageID, string RelatesTo, MaintainGeneralizedCodeNS.WSDLMaintainGeneralizedCodeResponseType maintainGeneralizedCodeResponse)
        {
            this.To = To;
            this.Action = Action;
            this.MessageID = MessageID;
            this.RelatesTo = RelatesTo;
            this.maintainGeneralizedCodeResponse = maintainGeneralizedCodeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface QdocWebServiceChannel : MaintainGeneralizedCodeNS.QdocWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class QdocWebServiceClient : System.ServiceModel.ClientBase<MaintainGeneralizedCodeNS.QdocWebService>, MaintainGeneralizedCodeNS.QdocWebService
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public QdocWebServiceClient() : 
                base(QdocWebServiceClient.GetDefaultBinding(), QdocWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.QdocWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QdocWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(QdocWebServiceClient.GetBindingForEndpoint(endpointConfiguration), QdocWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QdocWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(QdocWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QdocWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(QdocWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QdocWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeResponse> MaintainGeneralizedCodeNS.QdocWebService.maintainGeneralizedCodeAsync(MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeRequest request)
        {
            return base.Channel.maintainGeneralizedCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeResponse> maintainGeneralizedCodeAsync(string Action, string To, string MessageID, MaintainGeneralizedCodeNS.ReferenceParametersType ReferenceParameters, MaintainGeneralizedCodeNS.ReplyToType ReplyTo, MaintainGeneralizedCodeNS.WSDLMaintainGeneralizedCodeType maintainGeneralizedCode)
        {
            MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeRequest inValue = new MaintainGeneralizedCodeNS.processMaintainGeneralizedCodeRequest();
            inValue.Action = Action;
            inValue.To = To;
            inValue.MessageID = MessageID;
            inValue.ReferenceParameters = ReferenceParameters;
            inValue.ReplyTo = ReplyTo;
            inValue.maintainGeneralizedCode = maintainGeneralizedCode;
            return ((MaintainGeneralizedCodeNS.QdocWebService)(this)).maintainGeneralizedCodeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.QdocWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.QdocWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://twerp.taiwayltd.com.tw:22895/qxi/services/QdocWebService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return QdocWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.QdocWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return QdocWebServiceClient.GetEndpointAddress(EndpointConfiguration.QdocWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            QdocWebService,
        }
    }
}
