//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessage
    {
        
        private ExchangeFaultData standardField;
        
        private StandardFaultMessageExtension additionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StandardFaultMessageExtension addition
        {
            get
            {
                return this.additionField;
            }
            set
            {
                this.additionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeFaultData
    {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText
        {
            get
            {
                return this.faultTextField;
            }
            set
            {
                this.faultTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl
        {
            get
            {
                return this.faultUrlField;
            }
            set
            {
                this.faultUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail
        {
            get
            {
                return this.faultDetailField;
            }
            set
            {
                this.faultDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeLogData
    {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessageExtension
    {
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Log Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Log
    {
        
        private string businessDocumentProcessingResultCodeField;
        
        private string maximumLogItemSeverityCodeField;
        
        private LogItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string BusinessDocumentProcessingResultCode
        {
            get
            {
                return this.businessDocumentProcessingResultCodeField;
            }
            set
            {
                this.businessDocumentProcessingResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string MaximumLogItemSeverityCode
        {
            get
            {
                return this.maximumLogItemSeverityCodeField;
            }
            set
            {
                this.maximumLogItemSeverityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LogItem[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItem
    {
        
        private string typeIDField;
        
        private LogItemCategoryCode categoryCodeField;
        
        private string severityCodeField;
        
        private string referenceObjectNodeSenderTechnicalIDField;
        
        private string referenceMessageElementNameField;
        
        private string noteField;
        
        private string noteTemplateTextField;
        
        private LogItemNotePlaceholderSubstitutionList logItemNotePlaceholderSubstitutionListField;
        
        private string webURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogItemCategoryCode CategoryCode
        {
            get
            {
                return this.categoryCodeField;
            }
            set
            {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string ReferenceObjectNodeSenderTechnicalID
        {
            get
            {
                return this.referenceObjectNodeSenderTechnicalIDField;
            }
            set
            {
                this.referenceObjectNodeSenderTechnicalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ReferenceMessageElementName
        {
            get
            {
                return this.referenceMessageElementNameField;
            }
            set
            {
                this.referenceMessageElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NoteTemplateText
        {
            get
            {
                return this.noteTemplateTextField;
            }
            set
            {
                this.noteTemplateTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public LogItemNotePlaceholderSubstitutionList LogItemNotePlaceholderSubstitutionList
        {
            get
            {
                return this.logItemNotePlaceholderSubstitutionListField;
            }
            set
            {
                this.logItemNotePlaceholderSubstitutionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=8)]
        public string WebURI
        {
            get
            {
                return this.webURIField;
            }
            set
            {
                this.webURIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemCategoryCode
    {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private string listAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID
        {
            get
            {
                return this.listVersionIDField;
            }
            set
            {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID
        {
            get
            {
                return this.listAgencyIDField;
            }
            set
            {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID
        {
            get
            {
                return this.listAgencySchemeIDField;
            }
            set
            {
                this.listAgencySchemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencySchemeAgencyID
        {
            get
            {
                return this.listAgencySchemeAgencyIDField;
            }
            set
            {
                this.listAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemNotePlaceholderSubstitutionList
    {
        
        private string firstPlaceholderIDField;
        
        private string secondPlaceholderIDField;
        
        private string thirdPlaceholderIDField;
        
        private string fourthPlaceholderIDField;
        
        private string firstPlaceholderSubstitutionTextField;
        
        private string secondPlaceholderSubstitutionTextField;
        
        private string thirdPlaceholderSubstitutionTextField;
        
        private string fourthPlaceholderSubstitutionTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string FirstPlaceholderID
        {
            get
            {
                return this.firstPlaceholderIDField;
            }
            set
            {
                this.firstPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SecondPlaceholderID
        {
            get
            {
                return this.secondPlaceholderIDField;
            }
            set
            {
                this.secondPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ThirdPlaceholderID
        {
            get
            {
                return this.thirdPlaceholderIDField;
            }
            set
            {
                this.thirdPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string FourthPlaceholderID
        {
            get
            {
                return this.fourthPlaceholderIDField;
            }
            set
            {
                this.fourthPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FirstPlaceholderSubstitutionText
        {
            get
            {
                return this.firstPlaceholderSubstitutionTextField;
            }
            set
            {
                this.firstPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SecondPlaceholderSubstitutionText
        {
            get
            {
                return this.secondPlaceholderSubstitutionTextField;
            }
            set
            {
                this.secondPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ThirdPlaceholderSubstitutionText
        {
            get
            {
                return this.thirdPlaceholderSubstitutionTextField;
            }
            set
            {
                this.thirdPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FourthPlaceholderSubstitutionText
        {
            get
            {
                return this.fourthPlaceholderSubstitutionTextField;
            }
            set
            {
                this.fourthPlaceholderSubstitutionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class UUID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class GACDetails
    {
        
        private BusinessTransactionDocumentID externalGACIDField;
        
        private UUID gACUUIDField;
        
        private BusinessTransactionDocumentID gACIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessTransactionDocumentID ExternalGACID
        {
            get
            {
                return this.externalGACIDField;
            }
            set
            {
                this.externalGACIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID GACUUID
        {
            get
            {
                return this.gACUUIDField;
            }
            set
            {
                this.gACUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessTransactionDocumentID GACID
        {
            get
            {
                return this.gACIDField;
            }
            set
            {
                this.gACIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessTransactionDocumentID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeAgencySchemeAgencyID
        {
            get
            {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set
            {
                this.schemeAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class GoodsAndActivityConfirmationGoodsMovementResponse
    {
        
        private GACDetails[] gACDetailsField;
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GACDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GACDetails[] GACDetails
        {
            get
            {
                return this.gACDetailsField;
            }
            set
            {
                this.gACDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Log Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class INTEGER_Quantity
    {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unitCode
        {
            get
            {
                return this.unitCodeField;
            }
            set
            {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogisticUnitID
    {
        
        private string schemeIDField;
        
        private string schemeVersionIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeVersionID
        {
            get
            {
                return this.schemeVersionIDField;
            }
            set
            {
                this.schemeVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class GoodsAndActivityConfirmationInventoryChangeGACInventoryChangeItemLogisticUnitChangeQuantity
    {
        
        private LogisticUnitID logisticUnitIDField;
        
        private INTEGER_Quantity quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LogisticUnitID LogisticUnitID
        {
            get
            {
                return this.logisticUnitIDField;
            }
            set
            {
                this.logisticUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public INTEGER_Quantity Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class QuantityTypeCode
    {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private string listAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID
        {
            get
            {
                return this.listVersionIDField;
            }
            set
            {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID
        {
            get
            {
                return this.listAgencyIDField;
            }
            set
            {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID
        {
            get
            {
                return this.listAgencySchemeIDField;
            }
            set
            {
                this.listAgencySchemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencySchemeAgencyID
        {
            get
            {
                return this.listAgencySchemeAgencyIDField;
            }
            set
            {
                this.listAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Quantity
    {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unitCode
        {
            get
            {
                return this.unitCodeField;
            }
            set
            {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class GoodsAndActivityConfirmationInventoryChangeInventoryChangeItemInventoryItemChangeQuantity
    {
        
        private Quantity quantityField;
        
        private QuantityTypeCode quantityTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Quantity Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public QuantityTypeCode QuantityTypeCode
        {
            get
            {
                return this.quantityTypeCodeField;
            }
            set
            {
                this.quantityTypeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class IdentifiedStockID
    {
        
        private string schemeIDField;
        
        private string schemeVersionIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeVersionID
        {
            get
            {
                return this.schemeVersionIDField;
            }
            set
            {
                this.schemeVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class PartyInternalID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class ProductInternalID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class InventoryChangeItemGoodsMovement
    {
        
        private string externalItemIDField;
        
        private ProductInternalID materialInternalIDField;
        
        private PartyInternalID ownerPartyInternalIDField;
        
        private bool inventoryRestrictedUseIndicatorField;
        
        private InventoryStockStatusCode inventoryStockStatusCodeField;
        
        private bool inventoryStockStatusCodeFieldSpecified;
        
        private IdentifiedStockID identifiedStockIDField;
        
        private string sourceLogisticsAreaIDField;
        
        private string targetLogisticsAreaIDField;
        
        private GoodsAndActivityConfirmationInventoryChangeInventoryChangeItemInventoryItemChangeQuantity inventoryItemChangeQuantityField;
        
        private GoodsAndActivityConfirmationInventoryChangeGACInventoryChangeItemLogisticUnitChangeQuantity logisticUnitChangeQuantityField;
        
        private string[] inventoryItemChangeSerialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string ExternalItemID
        {
            get
            {
                return this.externalItemIDField;
            }
            set
            {
                this.externalItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductInternalID MaterialInternalID
        {
            get
            {
                return this.materialInternalIDField;
            }
            set
            {
                this.materialInternalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PartyInternalID OwnerPartyInternalID
        {
            get
            {
                return this.ownerPartyInternalIDField;
            }
            set
            {
                this.ownerPartyInternalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool InventoryRestrictedUseIndicator
        {
            get
            {
                return this.inventoryRestrictedUseIndicatorField;
            }
            set
            {
                this.inventoryRestrictedUseIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public InventoryStockStatusCode InventoryStockStatusCode
        {
            get
            {
                return this.inventoryStockStatusCodeField;
            }
            set
            {
                this.inventoryStockStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryStockStatusCodeSpecified
        {
            get
            {
                return this.inventoryStockStatusCodeFieldSpecified;
            }
            set
            {
                this.inventoryStockStatusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public IdentifiedStockID IdentifiedStockID
        {
            get
            {
                return this.identifiedStockIDField;
            }
            set
            {
                this.identifiedStockIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string SourceLogisticsAreaID
        {
            get
            {
                return this.sourceLogisticsAreaIDField;
            }
            set
            {
                this.sourceLogisticsAreaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string TargetLogisticsAreaID
        {
            get
            {
                return this.targetLogisticsAreaIDField;
            }
            set
            {
                this.targetLogisticsAreaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public GoodsAndActivityConfirmationInventoryChangeInventoryChangeItemInventoryItemChangeQuantity InventoryItemChangeQuantity
        {
            get
            {
                return this.inventoryItemChangeQuantityField;
            }
            set
            {
                this.inventoryItemChangeQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public GoodsAndActivityConfirmationInventoryChangeGACInventoryChangeItemLogisticUnitChangeQuantity LogisticUnitChangeQuantity
        {
            get
            {
                return this.logisticUnitChangeQuantityField;
            }
            set
            {
                this.logisticUnitChangeQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SerialID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", IsNullable=false)]
        public string[] InventoryItemChangeSerialNumber
        {
            get
            {
                return this.inventoryItemChangeSerialNumberField;
            }
            set
            {
                this.inventoryItemChangeSerialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public enum InventoryStockStatusCode
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LocationID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencySchemeID
        {
            get
            {
                return this.schemeAgencySchemeIDField;
            }
            set
            {
                this.schemeAgencySchemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeAgencySchemeAgencyID
        {
            get
            {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set
            {
                this.schemeAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global")]
    public partial class GoodsAndActivityConfirmationGoodsMoveGAC
    {
        
        private BusinessTransactionDocumentID externalIDField;
        
        private LocationID siteIDField;
        
        private System.DateTime transactionDateTimeField;
        
        private bool transactionDateTimeFieldSpecified;
        
        private InventoryChangeItemGoodsMovement[] inventoryChangeItemGoodsMovementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessTransactionDocumentID ExternalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LocationID SiteID
        {
            get
            {
                return this.siteIDField;
            }
            set
            {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime TransactionDateTime
        {
            get
            {
                return this.transactionDateTimeField;
            }
            set
            {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDateTimeSpecified
        {
            get
            {
                return this.transactionDateTimeFieldSpecified;
            }
            set
            {
                this.transactionDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InventoryChangeItemGoodsMovement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public InventoryChangeItemGoodsMovement[] InventoryChangeItemGoodsMovement
        {
            get
            {
                return this.inventoryChangeItemGoodsMovementField;
            }
            set
            {
                this.inventoryChangeItemGoodsMovementField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sap.com/xi/AP/LogisticsExecution/Global", ConfigurationName="InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcess" +
        "ingGoodsAndActivityConfirmationGoodsMovementIn")]
    public interface InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/AP/LogisticsExecution/Global/InventoryProcessingGoodsAndActivit" +
            "yConfirmationGoodsMovementIn/DoGoodsMovementGoodsAndActivityConfirmationRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.StandardFaultMessage), Action="http://sap.com/xi/AP/LogisticsExecution/Global/InventoryProcessingGoodsAndActivit" +
            "yConfirmationGoodsMovementIn/DoGoodsMovementGoodsAndActivityConfirmationRequest", Name="StandardFaultMessage", Namespace="http://sap.com/xi/AP/Common/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationResponse> DoGoodsMovementGoodsAndActivityConfirmationAsync(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoGoodsMovementGoodsAndActivityConfirmationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GoodsAndActivityConfirmation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.GoodsAndActivityConfirmationGoodsMoveGAC[] GoodsAndActivityConfirmationGoodsMovement;
        
        public DoGoodsMovementGoodsAndActivityConfirmationRequest()
        {
        }
        
        public DoGoodsMovementGoodsAndActivityConfirmationRequest(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.GoodsAndActivityConfirmationGoodsMoveGAC[] GoodsAndActivityConfirmationGoodsMovement)
        {
            this.GoodsAndActivityConfirmationGoodsMovement = GoodsAndActivityConfirmationGoodsMovement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoGoodsMovementGoodsAndActivityConfirmationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.GoodsAndActivityConfirmationGoodsMovementResponse GoodsAndActivityConfoirmationGoodsMovementResponse;
        
        public DoGoodsMovementGoodsAndActivityConfirmationResponse()
        {
        }
        
        public DoGoodsMovementGoodsAndActivityConfirmationResponse(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.GoodsAndActivityConfirmationGoodsMovementResponse GoodsAndActivityConfoirmationGoodsMovementResponse)
        {
            this.GoodsAndActivityConfoirmationGoodsMovementResponse = GoodsAndActivityConfoirmationGoodsMovementResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInChannel : InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInClient : System.ServiceModel.ClientBase<InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn>, InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn
    {
        
        public InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationResponse> InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn.DoGoodsMovementGoodsAndActivityConfirmationAsync(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationRequest request)
        {
            return base.Channel.DoGoodsMovementGoodsAndActivityConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationResponse> DoGoodsMovementGoodsAndActivityConfirmationAsync(InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.GoodsAndActivityConfirmationGoodsMoveGAC[] GoodsAndActivityConfirmationGoodsMovement)
        {
            InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationRequest inValue = new InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.DoGoodsMovementGoodsAndActivityConfirmationRequest();
            inValue.GoodsAndActivityConfirmationGoodsMovement = GoodsAndActivityConfirmationGoodsMovement;
            return ((InventoryProcessingGoodsAndActivityConfirmationGoodsMovementInNS.InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn)(this)).DoGoodsMovementGoodsAndActivityConfirmationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
