//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageSiteLogisticsTaskInNS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessage
    {
        
        private ExchangeFaultData standardField;
        
        private StandardFaultMessageExtension additionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ExchangeFaultData standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public StandardFaultMessageExtension addition
        {
            get
            {
                return this.additionField;
            }
            set
            {
                this.additionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeFaultData
    {
        
        private string faultTextField;
        
        private string faultUrlField;
        
        private ExchangeLogData[] faultDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultText
        {
            get
            {
                return this.faultTextField;
            }
            set
            {
                this.faultTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultUrl
        {
            get
            {
                return this.faultUrlField;
            }
            set
            {
                this.faultUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faultDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExchangeLogData[] faultDetail
        {
            get
            {
                return this.faultDetailField;
            }
            set
            {
                this.faultDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class ExchangeLogData
    {
        
        private string severityField;
        
        private string textField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemNotePlaceholderSubstitutionList
    {
        
        private string firstPlaceholderIDField;
        
        private string secondPlaceholderIDField;
        
        private string thirdPlaceholderIDField;
        
        private string fourthPlaceholderIDField;
        
        private string firstPlaceholderSubstitutionTextField;
        
        private string secondPlaceholderSubstitutionTextField;
        
        private string thirdPlaceholderSubstitutionTextField;
        
        private string fourthPlaceholderSubstitutionTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string FirstPlaceholderID
        {
            get
            {
                return this.firstPlaceholderIDField;
            }
            set
            {
                this.firstPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SecondPlaceholderID
        {
            get
            {
                return this.secondPlaceholderIDField;
            }
            set
            {
                this.secondPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ThirdPlaceholderID
        {
            get
            {
                return this.thirdPlaceholderIDField;
            }
            set
            {
                this.thirdPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string FourthPlaceholderID
        {
            get
            {
                return this.fourthPlaceholderIDField;
            }
            set
            {
                this.fourthPlaceholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FirstPlaceholderSubstitutionText
        {
            get
            {
                return this.firstPlaceholderSubstitutionTextField;
            }
            set
            {
                this.firstPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SecondPlaceholderSubstitutionText
        {
            get
            {
                return this.secondPlaceholderSubstitutionTextField;
            }
            set
            {
                this.secondPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ThirdPlaceholderSubstitutionText
        {
            get
            {
                return this.thirdPlaceholderSubstitutionTextField;
            }
            set
            {
                this.thirdPlaceholderSubstitutionTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FourthPlaceholderSubstitutionText
        {
            get
            {
                return this.fourthPlaceholderSubstitutionTextField;
            }
            set
            {
                this.fourthPlaceholderSubstitutionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItemCategoryCode
    {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private string listAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID
        {
            get
            {
                return this.listVersionIDField;
            }
            set
            {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID
        {
            get
            {
                return this.listAgencyIDField;
            }
            set
            {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID
        {
            get
            {
                return this.listAgencySchemeIDField;
            }
            set
            {
                this.listAgencySchemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string listAgencySchemeAgencyID
        {
            get
            {
                return this.listAgencySchemeAgencyIDField;
            }
            set
            {
                this.listAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogItem
    {
        
        private string typeIDField;
        
        private LogItemCategoryCode categoryCodeField;
        
        private string severityCodeField;
        
        private string referenceObjectNodeSenderTechnicalIDField;
        
        private string referenceMessageElementNameField;
        
        private string noteField;
        
        private string noteTemplateTextField;
        
        private LogItemNotePlaceholderSubstitutionList logItemNotePlaceholderSubstitutionListField;
        
        private string webURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string TypeID
        {
            get
            {
                return this.typeIDField;
            }
            set
            {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogItemCategoryCode CategoryCode
        {
            get
            {
                return this.categoryCodeField;
            }
            set
            {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string ReferenceObjectNodeSenderTechnicalID
        {
            get
            {
                return this.referenceObjectNodeSenderTechnicalIDField;
            }
            set
            {
                this.referenceObjectNodeSenderTechnicalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ReferenceMessageElementName
        {
            get
            {
                return this.referenceMessageElementNameField;
            }
            set
            {
                this.referenceMessageElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NoteTemplateText
        {
            get
            {
                return this.noteTemplateTextField;
            }
            set
            {
                this.noteTemplateTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public LogItemNotePlaceholderSubstitutionList LogItemNotePlaceholderSubstitutionList
        {
            get
            {
                return this.logItemNotePlaceholderSubstitutionListField;
            }
            set
            {
                this.logItemNotePlaceholderSubstitutionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=8)]
        public string WebURI
        {
            get
            {
                return this.webURIField;
            }
            set
            {
                this.webURIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Log
    {
        
        private string businessDocumentProcessingResultCodeField;
        
        private string maximumLogItemSeverityCodeField;
        
        private LogItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string BusinessDocumentProcessingResultCode
        {
            get
            {
                return this.businessDocumentProcessingResultCodeField;
            }
            set
            {
                this.businessDocumentProcessingResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string MaximumLogItemSeverityCode
        {
            get
            {
                return this.maximumLogItemSeverityCodeField;
            }
            set
            {
                this.maximumLogItemSeverityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public LogItem[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/Global")]
    public partial class StandardFaultMessageExtension
    {
        
        private Log logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Log Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskBundleException
    {
        
        private string messageNoteField;
        
        private string severityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MessageNote
        {
            get
            {
                return this.messageNoteField;
            }
            set
            {
                this.messageNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskBundleLog
    {
        
        private string siteLogisticsTaskNodeNameField;
        
        private string siteLogisticsTaskNodeIDField;
        
        private string siteLogisticsTaskSeverityCodeField;
        
        private string siteLogisticsTaskNoteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SiteLogisticsTaskNodeName
        {
            get
            {
                return this.siteLogisticsTaskNodeNameField;
            }
            set
            {
                this.siteLogisticsTaskNodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SiteLogisticsTaskNodeID
        {
            get
            {
                return this.siteLogisticsTaskNodeIDField;
            }
            set
            {
                this.siteLogisticsTaskNodeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SiteLogisticsTaskSeverityCode
        {
            get
            {
                return this.siteLogisticsTaskSeverityCodeField;
            }
            set
            {
                this.siteLogisticsTaskSeverityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SiteLogisticsTaskNote
        {
            get
            {
                return this.siteLogisticsTaskNoteField;
            }
            set
            {
                this.siteLogisticsTaskNoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskBundleMaintainResponse
    {
        
        private BusinessTransactionDocumentID taskIDField;
        
        private UUID taskUUIDField;
        
        private SiteLogisticsTaskBundleLog[] siteLogisticsTaskLogField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessTransactionDocumentID TaskID
        {
            get
            {
                return this.taskIDField;
            }
            set
            {
                this.taskIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID TaskUUID
        {
            get
            {
                return this.taskUUIDField;
            }
            set
            {
                this.taskUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteLogisticsTaskLog", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SiteLogisticsTaskBundleLog[] SiteLogisticsTaskLog
        {
            get
            {
                return this.siteLogisticsTaskLogField;
            }
            set
            {
                this.siteLogisticsTaskLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessTransactionDocumentID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeAgencySchemeAgencyID
        {
            get
            {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set
            {
                this.schemeAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class UUID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskBundleMaintainResponseMessage_sync
    {
        
        private SiteLogisticsTaskBundleMaintainResponse[] siteLogisticsTaskResponseField;
        
        private SiteLogisticsTaskBundleException[] exceptionMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteLogisticsTaskResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SiteLogisticsTaskBundleMaintainResponse[] SiteLogisticsTaskResponse
        {
            get
            {
                return this.siteLogisticsTaskResponseField;
            }
            set
            {
                this.siteLogisticsTaskResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExceptionMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SiteLogisticsTaskBundleException[] ExceptionMessage
        {
            get
            {
                return this.exceptionMessageField;
            }
            set
            {
                this.exceptionMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskLogisticsPackageOutputManageBundle_Request
    {
        
        private UUID logisticsUnitUUIDField;
        
        private LogisticUnitID logisticsUnitIDField;
        
        private INTEGER_Quantity logisticsUnitQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID LogisticsUnitUUID
        {
            get
            {
                return this.logisticsUnitUUIDField;
            }
            set
            {
                this.logisticsUnitUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogisticUnitID LogisticsUnitID
        {
            get
            {
                return this.logisticsUnitIDField;
            }
            set
            {
                this.logisticsUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public INTEGER_Quantity LogisticsUnitQuantity
        {
            get
            {
                return this.logisticsUnitQuantityField;
            }
            set
            {
                this.logisticsUnitQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogisticUnitID
    {
        
        private string schemeIDField;
        
        private string schemeVersionIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeVersionID
        {
            get
            {
                return this.schemeVersionIDField;
            }
            set
            {
                this.schemeVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class INTEGER_Quantity
    {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unitCode
        {
            get
            {
                return this.unitCodeField;
            }
            set
            {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SLTMaterialOutputManageBundle_Request
    {
        
        private UUID materialOutputUUIDField;
        
        private ProductID productIDField;
        
        private string sourceLogisticsAreaIDPostSplitField;
        
        private string targetLogisticsAreaIDField;
        
        private Quantity actualQuantityField;
        
        private IdentifiedStockID identifiedStockIDField;
        
        private RequirementSpecificationID productRequirementSpecificationIDField;
        
        private bool inventoryRestrictedIndicatorField;
        
        private bool inventoryRestrictedIndicatorFieldSpecified;
        
        private LogisticsDeviationReasonCode logisticsDeviationReasonCodeField;
        
        private bool splitIndicatorField;
        
        private bool splitIndicatorFieldSpecified;
        
        private SiteLogisticsTaskLogisticsPackageOutputManageBundle_Request[] logisticsPackageOutputField;
        
        private string[] automaticIdentificationField;
        
        private string[] serialNumberField;
        
        private bool clearIdentifiedStockIDIndicatorField;
        
        private bool clearIdentifiedStockIDIndicatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID MaterialOutputUUID
        {
            get
            {
                return this.materialOutputUUIDField;
            }
            set
            {
                this.materialOutputUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductID ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SourceLogisticsAreaIDPostSplit
        {
            get
            {
                return this.sourceLogisticsAreaIDPostSplitField;
            }
            set
            {
                this.sourceLogisticsAreaIDPostSplitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string TargetLogisticsAreaID
        {
            get
            {
                return this.targetLogisticsAreaIDField;
            }
            set
            {
                this.targetLogisticsAreaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Quantity ActualQuantity
        {
            get
            {
                return this.actualQuantityField;
            }
            set
            {
                this.actualQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public IdentifiedStockID IdentifiedStockID
        {
            get
            {
                return this.identifiedStockIDField;
            }
            set
            {
                this.identifiedStockIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public RequirementSpecificationID ProductRequirementSpecificationID
        {
            get
            {
                return this.productRequirementSpecificationIDField;
            }
            set
            {
                this.productRequirementSpecificationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool InventoryRestrictedIndicator
        {
            get
            {
                return this.inventoryRestrictedIndicatorField;
            }
            set
            {
                this.inventoryRestrictedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryRestrictedIndicatorSpecified
        {
            get
            {
                return this.inventoryRestrictedIndicatorFieldSpecified;
            }
            set
            {
                this.inventoryRestrictedIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public LogisticsDeviationReasonCode LogisticsDeviationReasonCode
        {
            get
            {
                return this.logisticsDeviationReasonCodeField;
            }
            set
            {
                this.logisticsDeviationReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool SplitIndicator
        {
            get
            {
                return this.splitIndicatorField;
            }
            set
            {
                this.splitIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SplitIndicatorSpecified
        {
            get
            {
                return this.splitIndicatorFieldSpecified;
            }
            set
            {
                this.splitIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LogisticsPackageOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public SiteLogisticsTaskLogisticsPackageOutputManageBundle_Request[] LogisticsPackageOutput
        {
            get
            {
                return this.logisticsPackageOutputField;
            }
            set
            {
                this.logisticsPackageOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BarCodeText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] AutomaticIdentification
        {
            get
            {
                return this.automaticIdentificationField;
            }
            set
            {
                this.automaticIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SerialID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", IsNullable=false)]
        public string[] SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool ClearIdentifiedStockIDIndicator
        {
            get
            {
                return this.clearIdentifiedStockIDIndicatorField;
            }
            set
            {
                this.clearIdentifiedStockIDIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearIdentifiedStockIDIndicatorSpecified
        {
            get
            {
                return this.clearIdentifiedStockIDIndicatorFieldSpecified;
            }
            set
            {
                this.clearIdentifiedStockIDIndicatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class ProductID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class Quantity
    {
        
        private string unitCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string unitCode
        {
            get
            {
                return this.unitCodeField;
            }
            set
            {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class IdentifiedStockID
    {
        
        private string schemeIDField;
        
        private string schemeVersionIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeVersionID
        {
            get
            {
                return this.schemeVersionIDField;
            }
            set
            {
                this.schemeVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class RequirementSpecificationID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class LogisticsDeviationReasonCode
    {
        
        private string listAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID
        {
            get
            {
                return this.listAgencyIDField;
            }
            set
            {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskLogisticsPackageInputManageBundle_Request
    {
        
        private UUID logisticsUnitUUIDField;
        
        private LogisticUnitID logisticsUnitIDField;
        
        private INTEGER_Quantity logisticsUnitQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID LogisticsUnitUUID
        {
            get
            {
                return this.logisticsUnitUUIDField;
            }
            set
            {
                this.logisticsUnitUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LogisticUnitID LogisticsUnitID
        {
            get
            {
                return this.logisticsUnitIDField;
            }
            set
            {
                this.logisticsUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public INTEGER_Quantity LogisticsUnitQuantity
        {
            get
            {
                return this.logisticsUnitQuantityField;
            }
            set
            {
                this.logisticsUnitQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskMaterialInputManageBundle_Request
    {
        
        private UUID materialInputUUIDField;
        
        private ProductID productIDField;
        
        private string sourceLogisticsAreaIDField;
        
        private Quantity actualQuantityField;
        
        private IdentifiedStockID identifiedStockIDField;
        
        private RequirementSpecificationID productRequirementSpecificationIDField;
        
        private bool inventoryRestrictedIndicatorField;
        
        private bool inventoryRestrictedIndicatorFieldSpecified;
        
        private LogisticsDeviationReasonCode logisticsDeviationReasonCodeField;
        
        private bool splitIndicatorField;
        
        private bool splitIndicatorFieldSpecified;
        
        private SiteLogisticsTaskLogisticsPackageInputManageBundle_Request[] logisticsPackageInputField;
        
        private string[] automaticIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID MaterialInputUUID
        {
            get
            {
                return this.materialInputUUIDField;
            }
            set
            {
                this.materialInputUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductID ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SourceLogisticsAreaID
        {
            get
            {
                return this.sourceLogisticsAreaIDField;
            }
            set
            {
                this.sourceLogisticsAreaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Quantity ActualQuantity
        {
            get
            {
                return this.actualQuantityField;
            }
            set
            {
                this.actualQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public IdentifiedStockID IdentifiedStockID
        {
            get
            {
                return this.identifiedStockIDField;
            }
            set
            {
                this.identifiedStockIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public RequirementSpecificationID ProductRequirementSpecificationID
        {
            get
            {
                return this.productRequirementSpecificationIDField;
            }
            set
            {
                this.productRequirementSpecificationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool InventoryRestrictedIndicator
        {
            get
            {
                return this.inventoryRestrictedIndicatorField;
            }
            set
            {
                this.inventoryRestrictedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryRestrictedIndicatorSpecified
        {
            get
            {
                return this.inventoryRestrictedIndicatorFieldSpecified;
            }
            set
            {
                this.inventoryRestrictedIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public LogisticsDeviationReasonCode LogisticsDeviationReasonCode
        {
            get
            {
                return this.logisticsDeviationReasonCodeField;
            }
            set
            {
                this.logisticsDeviationReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool SplitIndicator
        {
            get
            {
                return this.splitIndicatorField;
            }
            set
            {
                this.splitIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SplitIndicatorSpecified
        {
            get
            {
                return this.splitIndicatorFieldSpecified;
            }
            set
            {
                this.splitIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LogisticsPackageInput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public SiteLogisticsTaskLogisticsPackageInputManageBundle_Request[] LogisticsPackageInput
        {
            get
            {
                return this.logisticsPackageInputField;
            }
            set
            {
                this.logisticsPackageInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BarCodeText", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] AutomaticIdentification
        {
            get
            {
                return this.automaticIdentificationField;
            }
            set
            {
                this.automaticIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsLotOperationActivityManageBundle_Request
    {
        
        private UUID operationActivityUUIDField;
        
        private bool deliverySplitIndicatorField;
        
        private bool deliverySplitIndicatorFieldSpecified;
        
        private SiteLogisticsTaskMaterialInputManageBundle_Request[] materialInputField;
        
        private SLTMaterialOutputManageBundle_Request[] materialOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID OperationActivityUUID
        {
            get
            {
                return this.operationActivityUUIDField;
            }
            set
            {
                this.operationActivityUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool DeliverySplitIndicator
        {
            get
            {
                return this.deliverySplitIndicatorField;
            }
            set
            {
                this.deliverySplitIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliverySplitIndicatorSpecified
        {
            get
            {
                return this.deliverySplitIndicatorFieldSpecified;
            }
            set
            {
                this.deliverySplitIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialInput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public SiteLogisticsTaskMaterialInputManageBundle_Request[] MaterialInput
        {
            get
            {
                return this.materialInputField;
            }
            set
            {
                this.materialInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MaterialOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public SLTMaterialOutputManageBundle_Request[] MaterialOutput
        {
            get
            {
                return this.materialOutputField;
            }
            set
            {
                this.materialOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskReferenceObjectManageBundle_Request
    {
        
        private UUID referenceObjectUUIDField;
        
        private SiteLogisticsLotOperationActivityManageBundle_Request[] operationActivityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UUID ReferenceObjectUUID
        {
            get
            {
                return this.referenceObjectUUIDField;
            }
            set
            {
                this.referenceObjectUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SiteLogisticsLotOperationActivityManageBundle_Request[] OperationActivity
        {
            get
            {
                return this.operationActivityField;
            }
            set
            {
                this.operationActivityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/BASIS/Global")]
    public partial class LOCALNORMALISED_DateTime
    {
        
        private string timeZoneCodeField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string timeZoneCode
        {
            get
            {
                return this.timeZoneCodeField;
            }
            set
            {
                this.timeZoneCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class UPPEROPEN_LOCALNORMALISED_DateTimePeriod
    {
        
        private LOCALNORMALISED_DateTime startDateTimeField;
        
        private LOCALNORMALISED_DateTime endDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public LOCALNORMALISED_DateTime StartDateTime
        {
            get
            {
                return this.startDateTimeField;
            }
            set
            {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LOCALNORMALISED_DateTime EndDateTime
        {
            get
            {
                return this.endDateTimeField;
            }
            set
            {
                this.endDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskMaintainBundleRequest
    {
        
        private BusinessTransactionDocumentID siteLogisticTaskIDField;
        
        private UUID siteLogisticTaskUUIDField;
        
        private System.DateTime actualExecutionOnField;
        
        private bool actualExecutionOnFieldSpecified;
        
        private System.DateTime plannedStartDateField;
        
        private bool plannedStartDateFieldSpecified;
        
        private UPPEROPEN_LOCALNORMALISED_DateTimePeriod actualDeliveryDateField;
        
        private SiteLogisticsTaskReferenceObjectManageBundle_Request[] referenceObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessTransactionDocumentID SiteLogisticTaskID
        {
            get
            {
                return this.siteLogisticTaskIDField;
            }
            set
            {
                this.siteLogisticTaskIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID SiteLogisticTaskUUID
        {
            get
            {
                return this.siteLogisticTaskUUIDField;
            }
            set
            {
                this.siteLogisticTaskUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime ActualExecutionOn
        {
            get
            {
                return this.actualExecutionOnField;
            }
            set
            {
                this.actualExecutionOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActualExecutionOnSpecified
        {
            get
            {
                return this.actualExecutionOnFieldSpecified;
            }
            set
            {
                this.actualExecutionOnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime PlannedStartDate
        {
            get
            {
                return this.plannedStartDateField;
            }
            set
            {
                this.plannedStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlannedStartDateSpecified
        {
            get
            {
                return this.plannedStartDateFieldSpecified;
            }
            set
            {
                this.plannedStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public UPPEROPEN_LOCALNORMALISED_DateTimePeriod ActualDeliveryDate
        {
            get
            {
                return this.actualDeliveryDateField;
            }
            set
            {
                this.actualDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceObject", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public SiteLogisticsTaskReferenceObjectManageBundle_Request[] ReferenceObject
        {
            get
            {
                return this.referenceObjectField;
            }
            set
            {
                this.referenceObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessDocumentMessageID
    {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID
        {
            get
            {
                return this.schemeAgencyIDField;
            }
            set
            {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeAgencySchemeAgencyID
        {
            get
            {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set
            {
                this.schemeAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/AP/Common/GDT")]
    public partial class BusinessDocumentBasicMessageHeader
    {
        
        private BusinessDocumentMessageID idField;
        
        private UUID uUIDField;
        
        private BusinessDocumentMessageID referenceIDField;
        
        private UUID referenceUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentMessageID ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessDocumentMessageID ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UUID ReferenceUUID
        {
            get
            {
                return this.referenceUUIDField;
            }
            set
            {
                this.referenceUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/A1S/Global")]
    public partial class SiteLogisticsTaskMaintainRequestBundleMessage
    {
        
        private BusinessDocumentBasicMessageHeader basicMessageHeaderField;
        
        private SiteLogisticsTaskMaintainBundleRequest[] siteLogisticsTaskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentBasicMessageHeader BasicMessageHeader
        {
            get
            {
                return this.basicMessageHeaderField;
            }
            set
            {
                this.basicMessageHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SiteLogisticsTask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SiteLogisticsTaskMaintainBundleRequest[] SiteLogisticsTask
        {
            get
            {
                return this.siteLogisticsTaskField;
            }
            set
            {
                this.siteLogisticsTaskField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sap.com/xi/A1S/Global", ConfigurationName="ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn")]
    public interface ManageSiteLogisticsTaskIn
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/A1S/Global/ManageSiteLogisticsTaskIn/MaintainBundle_V1Request", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ManageSiteLogisticsTaskInNS.StandardFaultMessage), Action="http://sap.com/xi/A1S/Global/ManageSiteLogisticsTaskIn/MaintainBundle_V1Request", Name="StandardFaultMessage", Namespace="http://sap.com/xi/AP/Common/Global")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ManageSiteLogisticsTaskInNS.MaintainBundle_V1Response> MaintainBundle_V1Async(ManageSiteLogisticsTaskInNS.MaintainBundle_V1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaintainBundle_V1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public ManageSiteLogisticsTaskInNS.SiteLogisticsTaskMaintainRequestBundleMessage SiteLogisticsTaskBundleMaintainRequest_sync_V1;
        
        public MaintainBundle_V1Request()
        {
        }
        
        public MaintainBundle_V1Request(ManageSiteLogisticsTaskInNS.SiteLogisticsTaskMaintainRequestBundleMessage SiteLogisticsTaskBundleMaintainRequest_sync_V1)
        {
            this.SiteLogisticsTaskBundleMaintainRequest_sync_V1 = SiteLogisticsTaskBundleMaintainRequest_sync_V1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaintainBundle_V1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public ManageSiteLogisticsTaskInNS.SiteLogisticsTaskBundleMaintainResponseMessage_sync SiteLogisticsTaskBundleMaintainResponse_sync_V1;
        
        public MaintainBundle_V1Response()
        {
        }
        
        public MaintainBundle_V1Response(ManageSiteLogisticsTaskInNS.SiteLogisticsTaskBundleMaintainResponseMessage_sync SiteLogisticsTaskBundleMaintainResponse_sync_V1)
        {
            this.SiteLogisticsTaskBundleMaintainResponse_sync_V1 = SiteLogisticsTaskBundleMaintainResponse_sync_V1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ManageSiteLogisticsTaskInChannel : ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ManageSiteLogisticsTaskInClient : System.ServiceModel.ClientBase<ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn>, ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn
    {
        
        public ManageSiteLogisticsTaskInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManageSiteLogisticsTaskInNS.MaintainBundle_V1Response> ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn.MaintainBundle_V1Async(ManageSiteLogisticsTaskInNS.MaintainBundle_V1Request request)
        {
            return base.Channel.MaintainBundle_V1Async(request);
        }
        
        public System.Threading.Tasks.Task<ManageSiteLogisticsTaskInNS.MaintainBundle_V1Response> MaintainBundle_V1Async(ManageSiteLogisticsTaskInNS.SiteLogisticsTaskMaintainRequestBundleMessage SiteLogisticsTaskBundleMaintainRequest_sync_V1)
        {
            ManageSiteLogisticsTaskInNS.MaintainBundle_V1Request inValue = new ManageSiteLogisticsTaskInNS.MaintainBundle_V1Request();
            inValue.SiteLogisticsTaskBundleMaintainRequest_sync_V1 = SiteLogisticsTaskBundleMaintainRequest_sync_V1;
            return ((ManageSiteLogisticsTaskInNS.ManageSiteLogisticsTaskIn)(this)).MaintainBundle_V1Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
